on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  build-and-test:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - name: Set up Haskell
      uses: haskell/actions/setup@v2

    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Read the Cabal cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          message-index/dist-newstyle
        key: cabal-cache-${{ github.sha }}
        restore-keys: |
          cabal-cache

    - name: Update the Cabal index
      run: cabal update

    - name: Check if site.hs is formatted using ormolu
      uses: mrkkrp/ormolu-action@v6
      with:
        pattern: |
          **/site.hs

    - name: Build with Hakyll
      working-directory: message-index
      run: cabal run site build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./message-index/_site